### ISSUE TITLE
Crear archivo CHANGELOG

### ISSUE THREAD

**Issue by abr4xas** [abr4xas/node-instapago#5]
Actualmente hay un archivo llamado `CHANGELOG` y su contenido es algo asi:

```
31md784ec3[m - [32mabr4xas[m - [33m[m deleted [32m(7 minutes ago)[m
* [31m528abb5[m - [32mabr4xas[m - [33m[m Actualizado README. Agregado ejemplo del voucher [32m(7 minutes ago)[mm
```
Se me ocurre que podamos usar esto
http://keepachangelog.com

Acá el repo https://github.com/olivierlacan/keep-a-changelog

**Comment by jobsamuel** [comment]
Me gusta esa propuesta para el `CHANGELOG` :smiley: De hecho, he visto varios repos que utilizan el mismo estilo; su legibilidad y consistencia es genial.

Vamos a usarlo :+1:

**Comment by abr4xas** [comment]
Ok, fino entonces. Vamos usarlo para la `v0.3.0` cuando logremos usar todos los endpoints de instapago.
